services:
  mongodb:
    image: mongo:8.0
    container_name: courier_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: courier_service_db
    volumes:
      - mongodb_data:/data/db
    networks:
      - courier_network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: courier_api
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDbSettings__ConnectionString=mongodb://mongodb:27017
      - MongoDbSettings__DatabaseName=courier_service_db
    depends_on:
      - mongodb
    networks:
      - courier_network

volumes:
  mongodb_data:

networks:
  courier_network:
    driver: bridge
